---
# Deploy a VM from a template using Ansible 'vmware_guest' module
- name: Deploy VM from template
  vmware_guest:
    hostname: '{{ deploy_vsphere_host }}'
    username: '{{ deploy_vsphere_user }}'
    password: '{{ deploy_vsphere_password }}'
    validate_certs: no
    datacenter: '{{ deploy_vsphere_datacenter }}'
    cluster: '{{ deploy_vsphere_cluster }}'
    folder: '{{ deploy_vsphere_folder }}'
    name: '{{ inventory_hostname }}'
    guest_id: '{{ guest_id }}'
    annotation: "{{ guest_notes }}"
    disk:
    - size_gb: '{{ guest_storage }}'
      datastore: '{{ deploy_vsphere_datastore }}'
    networks:
    - name: '{{ guest_network }}'
      type: '{{ guest_netip_assign_type }}'
      gateway: '{{ guest_gateway }}'
      dns_servers:
      - '{{ guest_dns_server }}'
      - 8.8.8.8
    hardware:
      memory_gb: '{{ guest_custom_vmem }}'
      num_cpus: '{{ guest_custom_vcpu }}'
    customization:
      dns_servers:
      - '{{ guest_dns_server }}'
      - 8.8.8.8
      domain : '{{ guest_domain_name }}'
      hostname: '{{ inventory_hostname }}'  
    template: '{{ guest_template }}'
    wait_for_ip_address: yes
    state: poweredon
  delegate_to: localhost
