---                               
- name: Create New Users          
  hosts: all                      
  gather_facts: false             
  tasks:                          
    - name: Create Users Task  
      user:                       
        name: devops       
        state: present            
        password: "{{ default_user_password | password_hash('sha512', 'A512') }}"
        shell: /bin/bash   
